export const ELECTRON_EVENT = {
  GET_KLINE: 'GET_KLINE',
  ELECTRON_LOG: 'ELECTRON_LOG',
  CHANGE_NOTIFICATION_STATUS: 'CHANGE_NOTIFICATION_STATUS',
  NOTIFICATION: 'NOTIFICATION',
  GET_KLINE_ALL: 'GET_KLINE_ALL'
}
